// This file is generated by Firebase Genkit.
'use server';

/**
 * @fileOverview Suggests aiming point, power percentage, and cue ball spin for a selected shot.
 *
 * - suggestShotParameters - A function that suggests shot parameters.
 * - SuggestShotParametersInput - The input type for the suggestShotParameters function.
 * - SuggestShotParametersOutput - The return type for the suggestShotParameters function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const SuggestShotParametersInputSchema = z.object({
  ballPositions: z
    .array(z.object({
      x: z.number().describe('X coordinate of the ball on the table.'),
      y: z.number().describe('Y coordinate of the ball on the table.'),
    }))
    .describe('Array of ball positions on the table.'),
  targetPocket: z
    .enum(['top-left', 'top-middle', 'top-right', 'bottom-left', 'bottom-middle', 'bottom-right'])
    .describe('The pocket the user is aiming for.'),
  numberOfRails: z
    .number()
    .min(0)
    .max(5)
    .describe('The number of rails the user wants to use for the shot.'),
  aimingMethod: z.enum(['ball-first', 'rail-first']).describe('The aiming method selected by the user.'),
});
export type SuggestShotParametersInput = z.infer<typeof SuggestShotParametersInputSchema>;

const SuggestShotParametersOutputSchema = z.object({
  aimingPoint: z.object({
    x: z.number().describe('X coordinate of the aiming point on the table.'),
    y: z.number().describe('Y coordinate of the aiming point on the table.'),
  }).describe('Suggested aiming point on the table.'),
  powerPercentage: z.number().describe('Suggested power percentage for the shot (0-100).'),
  cueBallSpin: z.object({
    x: z.number().describe('X component of the cue ball spin.'),
    y: z.number().describe('Y component of the cue ball spin.'),
  }).describe('Suggested cue ball spin.'),
});
export type SuggestShotParametersOutput = z.infer<typeof SuggestShotParametersOutputSchema>;

export async function suggestShotParameters(input: SuggestShotParametersInput): Promise<SuggestShotParametersOutput> {
  return suggestShotParametersFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestShotParametersPrompt',
  input: {schema: SuggestShotParametersInputSchema},
  output: {schema: SuggestShotParametersOutputSchema},
  prompt: `You are an expert pool player and coach. You will be given the positions of the balls on the table, the target pocket, the number of rails the user wants to use, and the aiming method the user has selected. You will then suggest an aiming point, power percentage, and cue ball spin for the shot.

Ball Positions:
{{#each ballPositions}}
  Ball {{@index}}: x={{this.x}}, y={{this.y}}
{{/each}}

Target Pocket: {{{targetPocket}}}
Number of Rails: {{{numberOfRails}}}
Aiming Method: {{{aimingMethod}}}

Suggest an aiming point, power percentage, and cue ball spin for the shot. Return the values in JSON format.

{{output}}`,
});

const suggestShotParametersFlow = ai.defineFlow(
  {
    name: 'suggestShotParametersFlow',
    inputSchema: SuggestShotParametersInputSchema,
    outputSchema: SuggestShotParametersOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
